#config file for stakingtax

networksBasics:
  chainRegistry: https://raw.githubusercontent.com/cosmos/chain-registry
  chainExtraPath: /master/
  chainInfo: /chain.json

networks:
#  - name: fetchhub
#    denom: fet
#    exponent: 18
#    feedenom: afet
#    keepConfigNode: true
#    tradePairs4Tax:       #tradePairs4Tax 
#      endpoint: binance
#      pairs:
#        - FETBTC
#        - BTCEUR

  - name: cosmoshub
    denom: atom
    exponent: 6  
    feedenom: uatom
    keepConfigNode: true
    tradePairs4Tax:
      endpoint: cbpro
      pairs:
        - ATOM-EUR
  
query:
  pageLimit: 10 #query in bunches of this
  txStepBack: 1 #in case we need to go backwards for matsching blockheight, start with this stepsize, doubled in each cycle
  nRetry: 100 #in case query result is invalid, how often should we retry
  tRetry: 20 #in case we retry, wait this amount of s before retrying
  
taxRelevantMessageTypes:
  - /cosmos.staking.v1beta1.MsgDelegate
  - /cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward
  - /cosmos.staking.v1beta1.MsgBeginRedelegate
  - /cosmos.authz.v1beta1.MsgExec
  - /cosmos.authz.v1beta1.MsgGrant
  - /cosmos.staking.v1beta1.MsgUndelegate


#tradePairs4Tax:
# enpoints for now are [cbpro]
# pairs lists the required pairs (in format used by the endpoint) to get to the base unit for tax, e.g. EUR. The conversion will happen in the given sequence. 
# trade pairs can be retrieved from: (easiest ist to search through the raw data in the browser) 
# cbpro: https://api.exchange.coinbase.com/products
# binance: https://api.binance.com/api/v3/exchangeInfo



#https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/chain.json  
#https://github.com/cosmos/chain-registry/blob/master/cosmoshub/assetlist.json
#https://github.com/cosmos/chain-registry/blob/master/fetchhub/chain.json
#https://github.com/cosmos/chain-registry/blob/master/cosmoshub/chain.json  